version: '3'
services:
  client:
    build: client
    container_name: mimea-client
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/tslint.json:/usr/src/app/tslint.json
    command: ng serve --host 0.0.0.0

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: mimea-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
    - ./blockchain/network:/usr/src/app/network
    - ./blockchain/shared:/usr/src/app/shared
    - ./blockchain/chaincode:/usr/src/app/chaincode
    command: npm run start --host 0.0.0.0
